{
  "S3BucketName": "your-s3-bucket-name",
  "FirehoseStreamName": "your-firehose-stream-name",
  "IoTRuleName": "your-iot-core-rule-name",
  "IoTTopicName": "your-iot-mqtt-topic-name",
  "DeviceTypes": ["DeviceType1", "DeviceType2", "DeviceType3"],
  "GlueDatabaseName": "dummy-db",
  "FirehoseBufferInterval": 300,
  "FirehoseBufferSize": 5
}
